spring:
  application:
    name: noctowl
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    #    url: jdbc:postgresql://host.docker.internal:5432/noctowl
    url: jdbc:postgresql://localhost:5432/noctowl
    username: root
    password: root-password

server:
  port: 8084

wikipedia:
  base-url: https://%s.wikipedia.org/api/rest_v1
wikimedia:
  base-url: https://api.wikimedia.org/core/v1
  user-agent: noctowl
wikidata:
  base-url: https://www.wikidata.org

gbif:
  base-url: https://api.gbif.org/v2